[http]
host = "0.0.0.0"
port = 8080
env = "dev"
mode = "debug"

[[mysql]]
role = "default"
host = "54.69.237.139"
port = 8082
username = "root"
password = "123456"
dbname = "xpbet-dev-dev"

[redis]
host = ["54.69.237.139:8084", "54.69.237.139:8085", "54.69.237.139:8086"]
username = ""
password = ""
serverName = ""
poolSize = 50
maxIdleConns = 50
minIdleConns = 20
prefix = "xpbet"
tls = true

